# tämä estää root-login
PermitRootLogin no

# sallii avaimet
PubkeyAuthentication yes

# salli vielä salasanan
PasswordAuthentication yes

# rajoittaa yrityksia
MaxAuthTries 3

# tämä on aikakatkaisu
LoginGraceTime 30
